FROM alpine:3.1

#update
RUN apk add --update python py-pip

#install app dependencies
RUN pip install flask

#bundle app source
COPY simpleapp.py /src/simpleapp.py

EXPOSE 8000
CMD ["python", "/src/simpleapp.py", "-p 8000"]
